### ISSUE TITLE
Doc Request: Usage of NoHashHasher<T> with HashMap::with_hasher(hasher)

### ISSUE THREAD

**Issue by darakian** [paritytech/nohash-hasher#5]
Hey, thanks for the library! You saved me a bit of time making something like this for myself, but can I ask for an addition to the docs on how to use `NoHashHasher<T>` with the HashMap::with_hasher constructor?

**Comment by twittner** [comment]
Generally, I recommend to use the [`IntMap`](https://github.com/paritytech/nohash-hasher/blob/master/src/lib.rs#L14) type alias.

Let's say you want a `HashMap` to map `u8` keys to `bool` values:

```rust
let m: IntMap<u8, bool> = IntMap::default();
```

If you want to use `HashMap::with_hasher`, then you could make use of the [`BuildNoHashHasher`](https://github.com/paritytech/nohash-hasher/blob/master/src/lib.rs#L20) type alias and write instead:

```rust
let m: HashMap::<u8, bool, BuildNoHashHasher<u8>> = 
    HashMap::with_hasher(BuildNoHashHasher::default());
```

And if you also prefer to expand `BuildNoHashHasher` this would become:

```rust
let m: HashMap::<u8, bool, BuildHasherDefault<NoHashHasher<u8>>> = 
    HashMap::with_hasher(BuildHasherDefault::default());
```

**Comment by darakian** [comment]
Cool. Thank you for the explanation! I've made a PR which adds two of these cases as examples in the rust docs.

**Comment by twittner** [comment]
I have added some comments in https://github.com/paritytech/nohash-hasher/commit/c91d7ed5dabbc652a1cfb1226eac2a5425849723.

**Comment by darakian** [comment]
Awesome. Thank you! :)
